### ISSUE TITLE
Use GitHub Packages auto-release unstable version.

### ISSUE THREAD

**Issue by septs** [telegraf/telegraf#1210]
like https://github.com/orgs/DimensionDev/packages

Use GitHub actions automate submit new release to GitHub packages.

So that we can easily use unstable version.
(e.q: we have been waiting for 4.0, but he will not release it now)

Without waiting for the release to https://npmjs.com

Workflow:
```yaml
name: Release

on:
  push:
    branches: [develop]

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - run: DimensionDev/github-token-action@latest
        with:
          registry: true
      - run: npm ci
      - name: Publish to GitHub Package (unstable)
        run: |
          jq '.name = "@telegraf/telegraf"' package.json > package-modified.json
          mv package-modified.json package.json

          VERSION=$(jq -r '.version' package.json)
          npm --no-git-tag-version version "$VERSION-$BUILD_VERSION"
          npm publish
```
