### ISSUE TITLE
Stage should not passThru by default

### ISSUE THREAD

**Issue by MKRhere** [telegraf/telegraf#1850]
> ⚠️ Note: Leave your opinions on this issue if you don't want this to happen. Upvote if you want it to happen.

Currently this code:

```TS
const scene = new Scene("demo");
scene.enter(ctx => ctx.reply("welcome"));
scene.command("scene", ctx => ctx.reply("inside scene"));
scene.command("leave", ctx => ctx.scene.leave());

bot.use(new Stage([scene]));
bot.use(session());

bot.command("hello", ctx => ctx.reply("ohayo"));
bot.command("enter", ctx => ctx.scene.enter("demo"));
bot.start();
```

With this input, behaves like this:

```YAML
User: /enter
Bot: welcome <- scene entered
User: /scene
Bot: inside scene <- handler inside scene responds
User: /hello
Bot: ohayou <- handler outside scene responds
```

The common expectation seems to be that once in a scene, handlers outside the scene do not work for this user. However, this is not the current behaviour. If no listeners on the scene match, Telegraf passes through and calls the next middleware.

This issue proposes this behaviour changes in v5, with the addition of an option to Stage:

```TS
new Stage([scene], { passThru: true })
```

`passThru` will be false by default, and will prevent users from escaping a scene. It can be set to true for current behaviour. Per-scene passThru may also be possible.
